server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/duelme}

privy:
  app-id: ${PRIVY_APP_ID}

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/swagger-ui
